export const backgrounds = {
  hearts: require("./hearts_feed.jpg"),
  togetherMain: require("./together_main.png"),
  togetherStory: require("./together_story.png"),
  togetherChat: require("./together_chat.png"),
  smoke: require("./ads_wallpaper.jpg"),
  nightCity: require("./rooms_neon.jpg"),
  menu: require("./menu_glass.jpg"),
  ads: require("./bg_ads.jpg"),
  now: require("./bg_now.jpg"),
  rooms: require("./bg_rooms.jpg"),
  profile: require("./bg_profile.jpg"),
  startOnyxV4: require("./start_onyx_v4.png"),
  togetherOldBridgeV4: require("./together_old_bridge_v4.jpg"),
  togetherOldBridgeV5: require("./together_old_bridge_v5.jpg"),
  nearbyOldCityV4: require("./nearby_old_city_v4.jpg"),
  nearbyOldCityV5: require("./nearby_old_city_v5.jpg"),
  chatsBlackGlassV4: require("./chats_black_glass_v4.png"),
  profileOnyxV4: require("./profile_onyx_v4.png"),
  startLighthouseV6: require("./v6/lighthouse_v6.jpg"),
  togetherObservatoryV6: require("./v6/observatory_v6.jpg"),
  togetherSearchLighthouseV6: require("./v6/lighthouse_v6.jpg"),
  nearbyHarborV6: require("./v6/harbor_v6.jpg"),
  chatCanalV6: require("./v6/canal_v6.jpg"),
  profileArchGardenV6: require("./v6/arch_garden_v6.jpg"),
  drawerLanternStreetV6: require("./v6/drawer_lantern_street_v6.jpg"),
} as const;

export type BackgroundKey = keyof typeof backgrounds;
