ALTER TABLE "user_activity_preferences" DROP CONSTRAINT "user_activity_preferences_activity_key_check";--> statement-breakpoint
ALTER TABLE "user_activity_preferences" ADD CONSTRAINT "user_activity_preferences_activity_key_check" CHECK ("user_activity_preferences"."activity_key" IN ('coffee_nearby', 'walk_nearby', 'bike_nearby', 'cinema_today', 'talk_nearby', 'evening_nearby', 'roller_skating_nearby', 'kayaking_nearby', 'fishing_nearby', 'sport_nearby', 'language_exchange_nearby', 'local_event_nearby', 'lunch_nearby', 'dinner_nearby', 'dessert_nearby', 'board_games_nearby', 'chess_nearby', 'book_club_nearby', 'study_work_nearby', 'skateboarding_nearby', 'running_nearby', 'gym_nearby', 'yoga_nearby', 'dance_nearby', 'football_nearby', 'basketball_nearby', 'volleyball_nearby', 'tennis_nearby', 'table_tennis_nearby', 'badminton_nearby', 'beach_swim_nearby', 'picnic_nearby', 'hiking_nearby', 'dog_walk_nearby', 'concert_nearby', 'museum_exhibition_nearby', 'theater_nearby', 'live_music_nearby', 'festival_nearby', 'photography_nearby', 'cooking_nearby', 'volunteering_nearby', 'gaming_nearby'));--> statement-breakpoint
INSERT INTO "nearby_room_types" ("key", "title", "status", "admin_approved", "sort_order") VALUES
  ('coffee_nearby', 'Coffee nearby', 'active', true, 10),
  ('walk_nearby', 'Walk nearby', 'active', true, 20),
  ('bike_nearby', 'Bike nearby', 'active', true, 30),
  ('cinema_today', 'Cinema today', 'active', true, 40),
  ('talk_nearby', 'Talk nearby', 'active', true, 50),
  ('evening_nearby', 'Evening nearby', 'active', true, 60),
  ('roller_skating_nearby', 'Roller skating nearby', 'active', true, 70),
  ('kayaking_nearby', 'Kayaking nearby', 'active', true, 80),
  ('fishing_nearby', 'Fishing nearby', 'active', true, 90),
  ('sport_nearby', 'Sport nearby', 'active', true, 100),
  ('language_exchange_nearby', 'Language exchange nearby', 'active', true, 110),
  ('local_event_nearby', 'Local event nearby', 'active', true, 120),
  ('lunch_nearby', 'Lunch nearby', 'active', true, 130),
  ('dinner_nearby', 'Dinner nearby', 'active', true, 140),
  ('dessert_nearby', 'Dessert nearby', 'active', true, 150),
  ('board_games_nearby', 'Board games nearby', 'active', true, 160),
  ('chess_nearby', 'Chess nearby', 'active', true, 170),
  ('book_club_nearby', 'Book club nearby', 'active', true, 180),
  ('study_work_nearby', 'Study or work nearby', 'active', true, 190),
  ('skateboarding_nearby', 'Skateboarding nearby', 'active', true, 200),
  ('running_nearby', 'Running nearby', 'active', true, 210),
  ('gym_nearby', 'Gym nearby', 'active', true, 220),
  ('yoga_nearby', 'Yoga nearby', 'active', true, 230),
  ('dance_nearby', 'Dance nearby', 'active', true, 240),
  ('football_nearby', 'Football nearby', 'active', true, 250),
  ('basketball_nearby', 'Basketball nearby', 'active', true, 260),
  ('volleyball_nearby', 'Volleyball nearby', 'active', true, 270),
  ('tennis_nearby', 'Tennis nearby', 'active', true, 280),
  ('table_tennis_nearby', 'Table tennis nearby', 'active', true, 290),
  ('badminton_nearby', 'Badminton nearby', 'active', true, 300),
  ('beach_swim_nearby', 'Beach or swim nearby', 'active', true, 310),
  ('picnic_nearby', 'Picnic nearby', 'active', true, 320),
  ('hiking_nearby', 'Hiking nearby', 'active', true, 330),
  ('dog_walk_nearby', 'Dog walk nearby', 'active', true, 340),
  ('concert_nearby', 'Concert nearby', 'active', true, 350),
  ('museum_exhibition_nearby', 'Museum or exhibition nearby', 'active', true, 360),
  ('theater_nearby', 'Theater nearby', 'active', true, 370),
  ('live_music_nearby', 'Live music nearby', 'active', true, 380),
  ('festival_nearby', 'Festival nearby', 'active', true, 390),
  ('photography_nearby', 'Photography nearby', 'active', true, 400),
  ('cooking_nearby', 'Cooking nearby', 'active', true, 410),
  ('volunteering_nearby', 'Volunteering nearby', 'active', true, 420),
  ('gaming_nearby', 'Gaming nearby', 'active', true, 430)
ON CONFLICT ("key") DO NOTHING;
