import React from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import ScreenShell from "@/components/ScreenShell";
import { useLocale } from "@/contexts/LocaleContext";
import * as growthApi from "@/services/api/growthApi";
import { theme } from "@/theme";

const KEYS=["messages","together","communityActivity","premiumAccount"] as const;
export default function PushPreferencesScreen(){const{t}=useLocale();const[prefs,setPrefs]=React.useState<growthApi.PushPreferences|null>(null);const[busy,setBusy]=React.useState(true);React.useEffect(()=>{void growthApi.getPushPreferences().then(setPrefs).finally(()=>setBusy(false));},[]);const toggle=async(key:typeof KEYS[number],value:boolean)=>{if(!prefs)return;const next={...prefs,[key]:value};setPrefs(next);try{setPrefs(await growthApi.updatePushPreferences({messages:next.messages,together:next.together,communityActivity:next.communityActivity,premiumAccount:next.premiumAccount}));}catch{setPrefs(prefs);}};return <ScreenShell title={t("pushPrefs.title")} showBack><ScrollView contentContainerStyle={styles.content}>{busy?<ActivityIndicator color={theme.colors.accent}/>:KEYS.map(key=><View key={key} style={styles.row}><View style={styles.copy}><Text style={styles.label}>{t(`pushPrefs.${key}`)}</Text><Text style={styles.help}>{t(`pushPrefs.${key}.help`)}</Text></View><Switch value={Boolean(prefs?.[key])} onValueChange={value=>void toggle(key,value)}/></View>)}<View style={styles.row}><View style={styles.copy}><Text style={styles.label}>{t("pushPrefs.transactional")}</Text><Text style={styles.help}>{t("pushPrefs.transactional.help")}</Text></View><Switch value disabled/></View></ScrollView></ScreenShell>}
const styles=StyleSheet.create({content:{padding:20,gap:8},row:{flexDirection:"row",alignItems:"center",gap:12,paddingVertical:14,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:theme.colors.borderSubtle},copy:{flex:1,gap:4},label:{color:theme.colors.text,fontSize:15,fontWeight:"800"},help:{color:theme.colors.subtext,fontSize:12,lineHeight:17}});
